### ISSUE TITLE
contig fasta file not created

### ISSUE THREAD

**Issue by mmcardozo** [LottePronk/whokaryote#2]
Hi, 
When running the whokaryote.py with --f option the multifasta files are not created. It looks like the get_euk_prok_fasta.sh cannot be found but gives no actual error but a "No such file or directory" when cheking the folder the multifasta files are missing. 

(whokaryote) mcardozo@ollie0:~$ whokaryote.py --contigs /work/ollie/mcardozo/MetaG_MetaT/Annotations/BLAST_redoPSWwvsAw/PSWwvsAw.fasta --outdir whokaryote_PSWwvsAw --f
Removing contigs with length < 5000 bp...
Total contigs checked:	4737 
Number of contigs >=5000bp:	89 
Number of contigs <5000bp and removed:	4648
Model with tiara predictions selected.
Running tiara with 1 thread...
Classification took 2.3246610164642334 seconds.
38.28515184350076 sequences per second.
311973.22743557015 base pairs per second.
Classification done.
First iteration statistics:
	archaea: 3
	bacteria: 24
	eukarya: 24
	organelle: 36
	unknown: 2
Second iteration statistics:
	mitochondrion: 5
	plastid: 30
	unknown: 1

Output saved to whokaryote_PSWwvsAw/tiara_pred.txt.
Log file saved to whokaryote_PSWwvsAw/log_tiara_pred.txt.

Running prodigal...
Prodigal gene prediction successful. Saving gene coordinate file...
Gene coordinate file saved.
Gene prediction took 2.754788637161255 seconds.
Calculating gene structure features with gene predictions...
File extension: GFF
Calculating features successful.
Calculating gene structure features took 0.05253171920776367 seconds.
Predicting contig class...
Using model with tiara predictions to predict contig class...
Used features:
        ratio_same_orientation  ID_general_avg  ID_general_std  gene_density  ...       ID_Q1       ID_Q3  rbs_ratio  tiara_pred
count               72.000000       72.000000       72.000000     72.000000  ...   72.000000   72.000000  72.000000   72.000000
mean                 0.924795      132.174348      107.922552      0.853839  ...   43.281250  148.638889   0.474499    1.277778
std                  0.213395      116.810949      119.455889      0.135664  ...   58.381364  157.399073   0.330764    0.826024
min                  0.000000        2.000000        0.000000      0.388574  ...    0.000000    0.000000   0.000000    0.000000
25%                  1.000000       55.504464       32.983720      0.823262  ...    9.375000   52.687500   0.178030    1.000000
50%                  1.000000       83.833333       72.452346      0.900565  ...   23.500000   96.500000   0.488095    2.000000
75%                  1.000000      178.125000      135.869940      0.936368  ...   49.625000  183.250000   0.750000    2.000000
max                  1.000000      485.571429      576.655717      0.999452  ...  311.000000  701.500000   1.000000    2.000000

[8 rows x 9 columns]
(72, 9)
Used model:  RF_T_RBS_310122_bal.joblib
/home/ollie/mcardozo/.conda/envs/whokaryote/lib/python3.8/site-packages/scikit_learn-1.0.2-py3.8-linux-x86_64.egg/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
Prediction successful! See output directory.
Predicting contig class took 0.7110660076141357 seconds.
Writing eukaryotic and prokaryotic contigs to separate fasta files. This can take very long...
bash: /home/ollie/mcardozo/.conda/envs/whokaryote/lib/python3.8/site-packages/Whokaryote-0.0.1-py3.8.egg/EGG-INFO/whokaryote_scripts/get_euk_prok_fasta.sh: No such file or directory
Writing contigs to separate fastas (eukaryote, prokaryote) successful.
(whokaryote) mcardozo@ollie0:~$ 

Thanks,
Magda

**Comment by LottePronk** [comment]
Hi Magda,

Sorry for the late reply! I fixed a couple of things and it should be working fine now. Could you try re-installing whokaryote and let me know how it goes? I recommend removing your current whokaryote conda environment and make a new one according to the instructions in the readme. You can use the prodigal GFF output and the tiara files from your previous run for your next one (just put them in your desired output directory). 

Kind regards,
Lotte
