### ISSUE TITLE
Why # Output contigs < # Input contigs

### ISSUE THREAD

**Issue by namnh7** [LottePronk/whokaryote#3]
I notice that the number of output contigs while using --f option (prokaryotic contigs + eukaryotic contigs) is smaller than the number of input contigs. I set --minsize is the size of the shortest contig in my dataset. Can anyone explain for me? Thanks a lot!

**Comment by LottePronk** [comment]
Hi namnh7, thank you for your question. 

It's possible that some contigs were predicted to have less than 2 genes on them. Whokaryote needs 2 or more genes on a contig to determine for example the intergenic distance and the gene density. Contigs with less than 2 genes are not condsidered by Whokaryote and therefore are not in the output files. Could you check if the missing contigs are indeed ones with < 2 genes?
